name: adwaita_icons
description: Package that contains all icons built for the Adwaita Theme (updated to flutter_svg 2.x.x)
version: 0.3.0
homepage: https://github.com/bleonard252-forks/adwaita_icons

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ">=2.0.0 <3.0.0"

flutter:
  assets:
    - assets/icons/
